-- One-off cleanup of data generated by automated testing during development.
-- Scoped narrowly to test-identifiable rows only — does not touch the
-- "hello" product or the real b3njaminbaya@gmail.com account.

delete from public.orders
where customer_email ilike '%nyuzi-qa-testing.com%'
   or customer_name ilike '%test%'
   or customer_name ilike '%qa %'
   or customer_name ilike '%debug%';
-- order_items cascade-delete automatically with their parent order.

delete from public.donations
where title ilike '%test%'
   or notes ilike '%playwright%'
   or notes ilike '%verification run%'
   or notes ilike '%automated test%';

delete from public.partner_applications
where email ilike '%nyuzi-qa-testing.com%'
   or organization ilike 'QA Studio'
   or full_name ilike '%Verification Tester%'
   or full_name ilike '%Test%';

delete from public.newsletter_signups
where email ilike '%nyuzi-qa-testing.com%'
   or email = 'reader@example.com';

delete from public.products
where title ilike 'QA Test%';

-- Cascades to public.profiles via the on-delete-cascade foreign key.
delete from auth.users
where email ilike '%nyuzi-qa-testing.com%';

-- Verify what's left:
select 'orders' as table_name, count(*) from public.orders
union all select 'donations', count(*) from public.donations
union all select 'partner_applications', count(*) from public.partner_applications
union all select 'newsletter_signups', count(*) from public.newsletter_signups
union all select 'products', count(*) from public.products
union all select 'profiles', count(*) from public.profiles;
